# Generated by Django 3.1.4 on 2020-12-10 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iin', models.CharField(max_length=12, unique=True, verbose_name='IIN of a borrower')),
                ('date_of_birth', models.DateField(verbose_name='Date of birth of a borrower')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name of a program')),
                ('min_sum', models.IntegerField(verbose_name='Minimal sum of a credit')),
                ('max_sum', models.IntegerField(verbose_name='Maximum sum of a credit')),
                ('min_age', models.IntegerField(verbose_name='Miniman age of a borrower')),
                ('max_age', models.IntegerField(verbose_name='Maximum age of a borrower')),
            ],
        ),
        migrations.CreateModel(
            name='Blacklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='credits.borrower', to_field='iin', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(verbose_name='Sum of an application')),
                ('status', models.BooleanField(verbose_name='Status of an application')),
                ('refusing_reason', models.TextField(verbose_name='Refusing reason of an application')),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', related_query_name='application', to='credits.borrower', verbose_name='Application borrower')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', related_query_name='request', to='credits.program', verbose_name='Application program')),
            ],
        ),
    ]
