# Generated by Django 3.1.4 on 2020-12-10 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklist',
            name='iin',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='credits.borrower', to_field='iin'),
        ),
    ]
