# Generated by Django 3.1.4 on 2020-12-10 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0002_auto_20201210_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='refusing_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Refusing reason of an application'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.BooleanField(blank=True, null=True, verbose_name='Status of an application'),
        ),
    ]
